[tool.black]
line-length = 120
target_version = ['py39']

[tool.isort]
profile="black"
line_length = 120

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
warn_unreachable = true
strict = true
plugins = "numpy.typing.mypy_plugin"

[tool.pytest.ini_options]
markers = [
    "livecorpus: runs on the live Cell Census data corpus",
]
