name: Python Linting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install black black[jupyter]
          python -m pip install isort
          python -m pip install flake8-bugbear
          python -m pip install mypy==0.982 types-setuptools types-requests numpy pytest
      - name: Python Black
        run: |
          python -m black --check --diff .
      - name: Python isort
        run: |
          python -m isort --check --diff .
      - name: Python style with flake8[bugbear]
        run: |
          python -m flake8 .
      - name: Check type annotations mypy
        run: |
          python -m mypy .
